### ISSUE TITLE
大佬，能弄个云编译吗？

### ISSUE THREAD

**Issue by science2468** [xiechangan123/luci-i18n-xray-zh-cn#1]
自己本地编译总是出错，没有排查到出错的原因。能麻烦大佬云编译成现成的吗？

**Comment by xiechangan123** [comment]
Fork我的中文包之后，把默认的分支调整为old就可以跟yichya/luci-app-xray的一起编译了。。。
![网页捕获_8-4-2023_191125_github com](https://user-images.githubusercontent.com/9552275/230718071-04654e7d-7455-47e0-af6e-280613efb9d5.jpeg)

**Comment by science2468** [comment]
谢谢！没弄成功，等现成。没有就算了。

**Comment by xiechangan123** [comment]
如果你用的是P3TERX/Actions-OpenWrt的云编译，在diy-part1.sh文件按照下图设置，就可以编译了。前提openwrt22.03+
![image](https://user-images.githubusercontent.com/9552275/230723094-ab0fe344-2ab8-4114-8b14-8d3671b0bfaa.png)

**Comment by science2468** [comment]
谢谢大佬的指导！我看了一下午的云编译文档，看的脑袋涨。我研究研究云编译文档。我没用过云编译，打算换新的支持openwrt的xray/v2ray插件。

**Comment by science2468** [comment]
> 如果你用的是P3TERX/Actions-OpenWrt的云编译，在diy-part1.sh文件按照下图设置，就可以编译了。前提openwrt22.03+
> ![image](https://user-images.githubusercontent.com/9552275/230723094-ab0fe344-2ab8-4114-8b14-8d3671b0bfaa.png)
> 

谢谢指导，有这个到时候我弄下。

**Comment by xiechangan123** [comment]
fork我的这个云编译 https://github.com/xiechangan123/OpenWrt-X86 默认只有xray插件，只支持X86 Intel 网卡软路由（物理机），系统openwrt master分支，固件力求做到最简

**Comment by science2468** [comment]
> fork我的这个云编译 https://github.com/xiechangan123/OpenWrt-X86 默认只有xray插件，只支持X86 Intel 网卡软路由（物理机），系统openwrt master分支，固件力求做到最简

谢谢大佬！那我就fork您的分支搞我自己喜欢的固件了。

**Comment by science2468** [comment]
大佬，谢谢您的指导，我没编译成功，因为我还是不会云编译，但是我在本地编译成功了！
